// Podaci preneseni iz aplikacije "Golden Tip" (prijevodi, tržišta, baze).
export type Lang = "hr" | "en";
export const I18N: Record<Lang, Record<string, string>> = {
  hr: {
    calc: "Izračunaj predikciju",
    prob: "Vjerojatnost",
    fair: "Fair odd",
    val: "Vrijednost",
    hw: "Domaćin",
    dr: "Neriješeno",
    aw: "Gost",
    safe: "ZLATNI TIP ✅",
    vly: "VRLO IZGLEDNO 💪",
    ly: "IZGLEDNO 👍",
    ry: "POVEĆAN RIZIK ⚠️",
    hrk: "VISOK RIZIK 🚫",
    exp: "Stručna analiza",
    tip: "ZLATNA PREPORUKA",
    hg: "Golovi domaćin (5 ut.)",
    ag: "Golovi gost (5 ut.)",
    hg10: "Golovi domaćin (10 ut.)",
    ag10: "Golovi gost (10 ut.)",
    xg: "xG domaćin",
    xga: "xG gost",
    h2hh: "H2H domaćin",
    h2ha: "H2H gost",
    bttsH: "BTTS domaćin (5 ut.)",
    bttsA: "BTTS gost (5 ut.)",
    cs5: "Clean sheet (5 ut.)",
    fts5: "Bez gola (5 ut.)",
    elo: "ELO razlika",
    fat: "Umor (0-5)",
    inj: "Ozljede",
    susp: "Suspenzije",
    wea: "Vrijeme",
    tmp: "Temp °C",
    wnd: "Vjetar km/h",
    imp: "Važnost",
    mom: "Zamah",
    lavg: "Prosjek lige",
    prs: "Presing (0-10)",
    sp: "Prekidi (0-10)",
    poss: "Posjed %",
    shots: "Udarci/ut",
    shotsOT: "U okvir/ut",
    o1: "Kvota 1",
    oX: "Kvota X",
    o2: "Kvota 2",
    oGG: "Kvota GG",
    oNG: "Kvota NG",
    ln: "Granica",
    bank: "Bankroll (€)",
    kel: "Kelly %",
    rbt: "Preporučeni ulog",
    bas: "Osnovno",
    adv: "Napredna statistika",
    odd: "Kvote",
    hist: "Povijest",
    noHist: "Nema predikcija",
    clr: "Očisti",
    pl: "Broj igrača",
    pn: "Ime",
    g: "Golovi",
    m: "Utakmice",
    po: "Pozicija",
    pen: "Penali",
    min: "Minutaža",
    fw: "Napadač",
    mf: "Vezni",
    df: "Branič",
    ng: "Bez gola",
    ggtip: "✅ GG - OBA DAJU GOL",
    ngtip: "❌ NG - BAREM JEDAN NE DAJE",
    overtip: "📈 OVER",
    undertip: "📉 UNDER",
    htip: "🏠 DOMAĆIN",
    dtip: "🤝 NERIJEŠENO",
    atip: "✈ GOST",
    formula: "Korištena formula",
    lambda: "Očekivani λ",
    trap: "⚠️ UPOZORENJE: Kladionica možda namešta kvotu! Provjeri odds - ako je prenizak za vjerojatnost, moguća zamka!",
    trapTitle: "DETEKCIJA ZAMKE",
    valueYes: "✅ VRIJEDAN TIP",
    valueNo: "⚠️ BEZ VRIJEDNOSTI",
    devBy: "developed by Goran Pavić",
    history: "Povijest",
    clearAll: "🗑 Očisti sve",
    noHistory: "Nema spremljenih predikcija",
    showAdv: "📊 Napredna statistika",
    advStats: "Napredna statistika",
    cornHome: "Korneri dom (5)",
    cornAway: "Korneri gost (5)",
    style: "Stil",
    possession: "Posjed",
    counter: "Kontra",
    direct: "Direktna",
    cardsHome: "Kartoni dom (5)",
    cardsAway: "Kartoni gost (5)",
    intensity: "Intenzitet",
    referee: "Sudija",
    low: "Nizak",
    medium: "Srednji",
    high: "Visok",
    derby: "Derbi",
    strict: "Strog",
    average: "Prosječan",
    lenient: "Blag",
    minHome: "Min. domaćin",
    minAway: "Min. gost",
    probability: "Vjerojatnost %",
    quota: "Kvota",
    handicap: "Hendikep",
    halfGoalPct: "% golova 1H",
    htLabel: "1. pol.",
    shLabel: "2. pol.",
    golova: "golova",
    da: "✅ DA",
    ne: "❌ NE",
    install: "Instaliraj Plava Zvijezda 2026",
    installBtn: "Instaliraj",
    settings: "Postavke",
    fontSz: "Veličina fonta",
    fontSm: "Malo",
    fontMd: "Srednje",
    fontLg: "Veliko",
    compactView: "Kompaktan prikaz",
    autoTheme: "Auto tema (dan/noć)",
    homeAdvPct: "Domaćinska prednost %",
    formWPct: "Težina forme %",
    h2hWPct: "Težina H2H %",
    weatherOn: "Uključi vremenski faktor",
    bankroll: "💰 Bankroll Tracker",
    currentBr: "Trenutni bankroll",
    addBet: "Dodaj oklade",
    matchName: "Utakmica",
    betDesc: "Kladba",
    stakeEu: "Ulog (€)",
    oddsVal: "Kvota",
    resultW: "✅ Dobitak",
    resultL: "❌ Gubitak",
    resultV: "🔄 Void",
    totalBets: "Ukupno oklada",
    wins: "Dobici",
    losses: "Gubici",
    roi: "ROI",
    profit: "Profit",
    multiBet: "🎰 Multi-bet gradnja",
    addToMulti: "+ Multi-bet",
    totalOdds: "Ukupne kvote",
    totalProb: "Ukupna vjerojatn.",
    clearMulti: "Očisti",
    buildMulti: "Gradi akumulator",
    tools: "🔧 Smart Alati",
    probConv: "Pretvarač Vjerojatn. → Kvota",
    stakeRec: "Kalkulator povrata uloga",
    countdown: "Odbrojavanje do utakmice",
    presets: "Predlošci (brzi unos)",
    prevLoss: "Prethodnog gubitka (€)",
    targetOdds: "Ciljana kvota",
    neededStake: "Potrebni ulog",
    savePreset: "Spremi predložak",
    loadPreset: "Učitaj predložak",
    presetName: "Naziv predloška",
    matchTime: "Datum/Vrijeme utakmice",
    exportCsv: "📥 Export CSV",
    filterConf: "Filter po sigurnosti",
    allLevels: "Sve razine",
    addNote: "Bilješka...",
    tagRisky: "🔴 Rizično",
    tagSafe: "🟢 Sigurno",
    tagValue: "💰 Vrijednost",
    tagTrap: "🚨 Zamka",
    share: "📤 Dijeli",
    shareOk: "Kopirano!",
    dailySum: "📅 Danas:",
    confMeter: "Pouzdanost",
    hg5: "Golovi domaćin (5 ut.)",
    ag5: "Golovi gost (5 ut.)",
    bttsHistH: "BTTS dom (od 5)",
    bttsHistA: "BTTS gost (od 5)",
    csH5: "Clean sheet dom (5)",
    csA5: "Clean sheet gost (5)",
    ftsH5: "Bez gola dom (5)",
    ftsA5: "Bez gola gost (5)",
    aiLavg: "Prosjek gol/ut u ligi",
    aiWea: "Vremenske prilike",
    aiInjH: "Ključne ozljede domaćin (0-5)",
    aiInjA: "Ključne ozljede gost (0-5)",
    aiImp: "Važnost utakmice",
    aiMom: "Zamah domaćina (-10 do +10)",
    aiHomeAdv: "Prednost domaćina % (0-30)",
    overH5: "Over 2.5 dom (od 5)",
    overA5: "Over 2.5 gost (od 5)",
    oOver: "Kvota Over 2.5",
    oUnder: "Kvota Under 2.5",
    aiGG: "GG vjerojatnost",
    aiNG: "NG vjerojatnost",
    aiOver: "Over vjerojatnost",
    aiUnder: "Under vjerojatnost",
    aiLamH: "λ domaćin",
    aiLamA: "λ gost",
    aiTotal: "λ ukupno",
    aiExpl: "Detaljna analiza AI",
    fairOddsGG: "Fair kvota GG",
    fairOddsNG: "Fair kvota NG",
    fairOddsOv: "Fair kvota Over",
    fairOddsUn: "Fair kvota Under",
    kellyGG: "Ulog Kelly GG",
    kellyNG: "Ulog Kelly NG",
    kellyOv: "Ulog Kelly Over",
    kellyUn: "Ulog Kelly Under",
    valueTrap: "🚨 ZAMKA - Kvota je preniska!",
    valuePos: "✅ POZITIVNA VRIJEDNOST",
    valueNeg: "⚠️ Nema vrijednosti",
    impFriendly: "Prijateljska",
    impLeague: "Liga",
    impCup: "Kup",
    impDerby: "Derbi",
    impFinal: "Finale",
    weaClear: "Vedro",
    weaRain: "Kiša",
    weaSnow: "Snijeg",
    weaWind: "Vjetar",
    kellyCalc: "📐 Kelly Kalkulator",
    favorites: "⭐ Favoriti",
    winStats: "📊 Statistika",
    saveFav: "Spremi kao favorit",
    noFavs: "Nema favorita",
    clearFavs: "Očisti favorite",
    totalPreds: "Ukupno predikcija",
    todayPreds: "Danas",
    highConf: "Visoka sigurnost",
    animCelebrate: "🎉 ODLIČNA PREDIKCIJA!",
  },
  en: {
    calc: "Calculate Prediction",
    prob: "Probability",
    fair: "Fair odd",
    val: "Value",
    hw: "Home",
    dr: "Draw",
    aw: "Away",
    safe: "GOLDEN TIP ✅",
    vly: "VERY LIKELY 💪",
    ly: "LIKELY 👍",
    ry: "INCREASED RISK ⚠️",
    hrk: "HIGH RISK 🚫",
    exp: "Expert Analysis",
    tip: "GOLDEN RECOMMENDATION",
    hg: "Home goals (5)",
    ag: "Away goals (5)",
    hg10: "Home goals (10)",
    ag10: "Away goals (10)",
    xg: "xG Home",
    xga: "xG Away",
    h2hh: "H2H Home",
    h2ha: "H2H Away",
    bttsH: "BTTS Home (5)",
    bttsA: "BTTS Away (5)",
    cs5: "Clean sheets (5)",
    fts5: "Failed to score (5)",
    elo: "ELO diff",
    fat: "Fatigue (0-5)",
    inj: "Injuries",
    susp: "Suspensions",
    wea: "Weather",
    tmp: "Temp °C",
    wnd: "Wind km/h",
    imp: "Importance",
    mom: "Momentum",
    lavg: "League avg",
    prs: "Pressing (0-10)",
    sp: "Set pieces (0-10)",
    poss: "Possession %",
    shots: "Shots/match",
    shotsOT: "On target/match",
    o1: "Odds 1",
    oX: "Odds X",
    o2: "Odds 2",
    oGG: "Odds GG",
    oNG: "Odds NG",
    ln: "Line",
    bank: "Bankroll (€)",
    kel: "Kelly %",
    rbt: "Recommended bet",
    bas: "Basic",
    adv: "Advanced Stats",
    odd: "Odds",
    hist: "History",
    noHist: "No predictions",
    clr: "Clear",
    pl: "Players",
    pn: "Name",
    g: "Goals",
    m: "Matches",
    po: "Position",
    pen: "Penalties",
    min: "Minutes",
    fw: "Forward",
    mf: "Midfielder",
    df: "Defender",
    ng: "No goal",
    ggtip: "✅ GG - BOTH SCORE",
    ngtip: "❌ NG - CLEAN SHEET",
    overtip: "📈 OVER",
    undertip: "📉 UNDER",
    htip: "🏠 HOME",
    dtip: "🤝 DRAW",
    atip: "✈ AWAY",
    formula: "Formula used",
    lambda: "Expected λ",
    trap: "⚠️ WARNING: Bookmaker may be setting a trap! Check odds - if too low for probability, possible trap!",
    trapTitle: "TRAP DETECTION",
    valueYes: "✅ VALUE BET",
    valueNo: "⚠️ NO VALUE",
    devBy: "developed by Goran Pavić",
    history: "History",
    clearAll: "🗑 Clear all",
    noHistory: "No saved predictions",
    showAdv: "📊 Advanced Stats",
    advStats: "Advanced Stats",
    cornHome: "Corners home (5)",
    cornAway: "Corners away (5)",
    style: "Style",
    possession: "Possession",
    counter: "Counter",
    direct: "Direct",
    cardsHome: "Cards home (5)",
    cardsAway: "Cards away (5)",
    intensity: "Intensity",
    referee: "Referee",
    low: "Low",
    medium: "Medium",
    high: "High",
    derby: "Derby",
    strict: "Strict",
    average: "Average",
    lenient: "Lenient",
    minHome: "Min home",
    minAway: "Min away",
    probability: "Probability %",
    quota: "Odds",
    handicap: "Handicap",
    halfGoalPct: "% goals 1st H",
    htLabel: "1st H.",
    shLabel: "2nd H.",
    golova: "goals",
    da: "✅ YES",
    ne: "❌ NO",
    install: "Install Plava Zvijezda 2026",
    installBtn: "Install",
    settings: "Settings",
    fontSz: "Font size",
    fontSm: "Small",
    fontMd: "Medium",
    fontLg: "Large",
    compactView: "Compact view",
    autoTheme: "Auto theme (day/night)",
    homeAdvPct: "Home advantage %",
    formWPct: "Form weight %",
    h2hWPct: "H2H weight %",
    weatherOn: "Include weather factor",
    bankroll: "💰 Bankroll Tracker",
    currentBr: "Current bankroll",
    addBet: "Add bet",
    matchName: "Match",
    betDesc: "Bet",
    stakeEu: "Stake (€)",
    oddsVal: "Odds",
    resultW: "✅ Win",
    resultL: "❌ Loss",
    resultV: "🔄 Void",
    totalBets: "Total bets",
    wins: "Wins",
    losses: "Losses",
    roi: "ROI",
    profit: "Profit",
    multiBet: "🎰 Multi-bet Builder",
    addToMulti: "+ Multi-bet",
    totalOdds: "Total odds",
    totalProb: "Total prob.",
    clearMulti: "Clear",
    buildMulti: "Build accumulator",
    tools: "🔧 Smart Tools",
    probConv: "Probability → Odds Converter",
    stakeRec: "Stake Recovery Calculator",
    countdown: "Match Countdown",
    presets: "Presets (quick input)",
    prevLoss: "Previous loss (€)",
    targetOdds: "Target odds",
    neededStake: "Needed stake",
    savePreset: "Save preset",
    loadPreset: "Load preset",
    presetName: "Preset name",
    matchTime: "Match date/time",
    exportCsv: "📥 Export CSV",
    filterConf: "Filter by confidence",
    allLevels: "All levels",
    addNote: "Note...",
    tagRisky: "🔴 Risky",
    tagSafe: "🟢 Safe",
    tagValue: "💰 Value",
    tagTrap: "🚨 Trap",
    share: "📤 Share",
    shareOk: "Copied!",
    dailySum: "📅 Today:",
    confMeter: "Confidence",
    hg5: "Home goals (5 matches)",
    ag5: "Away goals (5 matches)",
    bttsHistH: "BTTS Home (of 5)",
    bttsHistA: "BTTS Away (of 5)",
    csH5: "Clean sheets Home (5)",
    csA5: "Clean sheets Away (5)",
    ftsH5: "Failed to score Home (5)",
    ftsA5: "Failed to score Away (5)",
    aiLavg: "League avg goals/match",
    aiWea: "Weather conditions",
    aiInjH: "Key injuries Home (0-5)",
    aiInjA: "Key injuries Away (0-5)",
    aiImp: "Match importance",
    aiMom: "Home momentum (-10 to +10)",
    aiHomeAdv: "Home advantage % (0-30)",
    overH5: "Over 2.5 Home (of 5)",
    overA5: "Over 2.5 Away (of 5)",
    oOver: "Odds Over 2.5",
    oUnder: "Odds Under 2.5",
    aiGG: "GG probability",
    aiNG: "NG probability",
    aiOver: "Over probability",
    aiUnder: "Under probability",
    aiLamH: "λ Home",
    aiLamA: "λ Away",
    aiTotal: "λ Total",
    aiExpl: "AI Detailed Analysis",
    fairOddsGG: "Fair odds GG",
    fairOddsNG: "Fair odds NG",
    fairOddsOv: "Fair odds Over",
    fairOddsUn: "Fair odds Under",
    kellyGG: "Kelly stake GG",
    kellyNG: "Kelly stake NG",
    kellyOv: "Kelly stake Over",
    kellyUn: "Kelly stake Under",
    valueTrap: "🚨 TRAP - Odds too low!",
    valuePos: "✅ POSITIVE VALUE",
    valueNeg: "⚠️ No value",
    impFriendly: "Friendly",
    impLeague: "League",
    impCup: "Cup",
    impDerby: "Derby",
    impFinal: "Final",
    weaClear: "Clear",
    weaRain: "Rain",
    weaSnow: "Snow",
    weaWind: "Wind",
    kellyCalc: "📐 Kelly Calculator",
    favorites: "⭐ Favorites",
    winStats: "📊 Statistics",
    saveFav: "Save as favorite",
    noFavs: "No favorites saved",
    clearFavs: "Clear favorites",
    totalPreds: "Total predictions",
    todayPreds: "Today",
    highConf: "High confidence",
    animCelebrate: "🎉 EXCELLENT PREDICTION!",
  },
};
export function t(key: string, lang: Lang): string {
  return I18N[lang][key] ?? I18N.hr[key] ?? key;
}
export type Section = { id: string; i: string; hr: string; en: string };
export const SECTIONS: Section[] = [
  { id: "1x2", i: "🎯", hr: "1X2 Ishodi", en: "1X2 Results" },
  { id: "btts", i: "⚽⚽", hr: "GG / NG (Oba tima)", en: "BTTS" },
  { id: "ou05", i: "0.5", hr: "Over/Under 0.5", en: "O/U 0.5" },
  { id: "ou15", i: "1.5", hr: "Over/Under 1.5", en: "O/U 1.5" },
  { id: "ou25", i: "2.5", hr: "Over/Under 2.5", en: "O/U 2.5" },
  { id: "ou35", i: "3.5", hr: "Over/Under 3.5", en: "O/U 3.5" },
  { id: "ou45", i: "4.5", hr: "Over/Under 4.5", en: "O/U 4.5" },
  { id: "ou55", i: "5.5", hr: "Over/Under 5.5", en: "O/U 5.5" },
  { id: "ou65", i: "6.5", hr: "Over/Under 6.5", en: "O/U 6.5" },
  { id: "cs", i: "🎪", hr: "Točan rezultat", en: "Correct Score" },
  { id: "dc", i: "🔒", hr: "Dvostruka šansa", en: "Double Chance" },
  { id: "htft", i: "🔄", hr: "Poluvrijeme/Kraj", en: "Half/Full Time" },
  { id: "ht1x2", i: "⏸🎯", hr: "1. pol. 1X2", en: "1st H 1X2" },
  { id: "htbtts", i: "⏸⚽", hr: "1. pol. GG/NG", en: "1st H BTTS" },
  { id: "htou05", i: "⏸0.5", hr: "1. pol. O/U 0.5", en: "1st H O/U 0.5" },
  { id: "htou15", i: "⏸1.5", hr: "1. pol. O/U 1.5", en: "1st H O/U 1.5" },
  { id: "sh1x2", i: "▶🎯", hr: "2. pol. 1X2", en: "2nd H 1X2" },
  { id: "shbtts", i: "▶⚽", hr: "2. pol. GG/NG", en: "2nd H BTTS" },
  { id: "shou05", i: "▶0.5", hr: "2. pol. O/U 0.5", en: "2nd H O/U 0.5" },
  { id: "shou15", i: "▶1.5", hr: "2. pol. O/U 1.5", en: "2nd H O/U 1.5" },
  { id: "ah05", i: "±0.5", hr: "Azijski H. ±0.5", en: "AH ±0.5" },
  { id: "ah15", i: "±1.5", hr: "Azijski H. ±1.5", en: "AH ±1.5" },
  { id: "ah25", i: "±2.5", hr: "Azijski H. ±2.5", en: "AH ±2.5" },
  { id: "corn", i: "🏳", hr: "Korneri ukupno", en: "Total Corners" },
  { id: "cornH", i: "🏳🏠", hr: "Korneri domaćin", en: "Home Corners" },
  { id: "cornA", i: "🏳✈", hr: "Korneri gost", en: "Away Corners" },
  { id: "cornO85", i: "🏳8.5", hr: "Korneri O8.5", en: "Corn O8.5" },
  { id: "cornO95", i: "🏳9.5", hr: "Korneri O9.5", en: "Corn O9.5" },
  { id: "cornO105", i: "🏳10.5", hr: "Korneri O10.5", en: "Corn O10.5" },
  { id: "cornO115", i: "🏳11.5", hr: "Korneri O11.5", en: "Corn O11.5" },
  { id: "cards", i: "🟨", hr: "Kartoni ukupno", en: "Total Cards" },
  { id: "cardsH", i: "🟨🏠", hr: "Kartoni domaćin", en: "Home Cards" },
  { id: "cardsA", i: "🟨✈", hr: "Kartoni gost", en: "Away Cards" },
  { id: "cardsO25", i: "🟨2.5", hr: "Kartoni O2.5", en: "Cards O2.5" },
  { id: "cardsO35", i: "🟨3.5", hr: "Kartoni O3.5", en: "Cards O3.5" },
  { id: "cardsO45", i: "🟨4.5", hr: "Kartoni O4.5", en: "Cards O4.5" },
  { id: "cardsO55", i: "🟨5.5", hr: "Kartoni O5.5", en: "Cards O5.5" },
  { id: "fg", i: "⏱", hr: "Vrijeme prvog gola", en: "First Goal Time" },
  { id: "fg15", i: "⏱15", hr: "Prvi gol <15 min", en: "1st G <15" },
  { id: "fg30", i: "⏱30", hr: "Prvi gol <30 min", en: "1st G <30" },
  { id: "hg", i: "🏠", hr: "Golovi domaćin", en: "Home Goals" },
  { id: "ag", i: "✈", hr: "Golovi gost", en: "Away Goals" },
  { id: "hgo15", i: "🏠1.5", hr: "Domaćin >1.5", en: "Home >1.5" },
  { id: "ago15", i: "✈1.5", hr: "Gost >1.5", en: "Away >1.5" },
  { id: "hgo25", i: "🏠2.5", hr: "Domaćin >2.5", en: "Home >2.5" },
  { id: "scorer", i: "👑", hr: "Prvi strijelac", en: "First Scorer" },
  { id: "winNil", i: "🧤", hr: "Pobjeda bez gola", en: "Win to Nil" },
  { id: "multi23", i: "🎰23", hr: "Točno 2-3 gola", en: "Exactly 2-3" },
  { id: "multi46", i: "🎰46", hr: "Točno 4-6 golova", en: "Exactly 4-6" },
  { id: "multi01", i: "🎰01", hr: "0-1 gol", en: "0-1 Goals" },
  { id: "multi7p", i: "🎰7+", hr: "7+ golova", en: "7+ Goals" },
  { id: "value", i: "💎", hr: "Value detektor", en: "Value Finder" },
  { id: "penalty", i: "🎯⚽", hr: "Hoće li biti penal", en: "Penalty Awarded" },
  { id: "redCard", i: "🟥", hr: "Hoće li biti crveni", en: "Red Card" },
  { id: "comeback", i: "🔄", hr: "Preokret (comeback)", en: "Comeback Win" },
  { id: "bothHalves", i: "⚽⚽", hr: "Gol u oba poluvremena", en: "Goal Both Halves" },
  { id: "domBoth", i: "🏠⚽⚽", hr: "Dom gol oba pol.", en: "Home Both Halves" },
  { id: "gostBoth", i: "✈⚽⚽", hr: "Gost gol oba pol.", en: "Away Both Halves" },
  { id: "cleanSheetH", i: "🧤🏠", hr: "Dom clean sheet", en: "Home CS" },
  { id: "cleanSheetA", i: "🧤✈", hr: "Gost clean sheet", en: "Away CS" },
  { id: "firstHalfWin", i: "⏸🏆", hr: "Vodi na poluvremenu", en: "Lead HT" },
  { id: "secondHalfWin", i: "▶🏆", hr: "Pobjeda u 2. pol.", en: "Win 2nd Half" },
  { id: "drawHT", i: "⏸🤝", hr: "Neriješeno na pol.", en: "Draw HT" },
  { id: "winFromBehind", i: "🔄🏆", hr: "Pobjeda iz zaostatka", en: "Win From Behind" },
  { id: "loseFromAhead", i: "📉😱", hr: "Poraz iz vodstva", en: "Lose From Ahead" },
  { id: "totalShots", i: "🎯📊", hr: "Ukupno udarci O/U", en: "Total Shots O/U" },
  { id: "shotsOnTarget", i: "🎯✅", hr: "Udarci u okvir O/U", en: "Shots OT O/U" },
  { id: "offsides", i: "🚩", hr: "Ofsajdi O/U", en: "Offsides O/U" },
  { id: "fouls", i: "💢", hr: "Prekršaji O/U", en: "Fouls O/U" },
  { id: "goalKicks", i: "🥅", hr: "Gol-auti O/U", en: "Goal Kicks O/U" },
  { id: "throwIns", i: "↗", hr: "Auti O/U", en: "Throw-ins O/U" },
  { id: "subs", i: "🔄👥", hr: "Izmjene O/U", en: "Subs O/U" },
  { id: "injuryTime", i: "⏰", hr: "Minutaža sudačka", en: "Injury Time O/U" },
  { id: "possession", i: "📊%", hr: "Posjed lopte O/U", en: "Possession O/U" },
  { id: "passAccuracy", i: "✅%", hr: "Točnost dodavanja", en: "Pass Accuracy O/U" },
  { id: "aerialDuels", i: "✈💪", hr: "Zračni dueli O/U", en: "Aerial Duels O/U" },
  { id: "tackles", i: "🛡", hr: "Oduzete lopte O/U", en: "Tackles O/U" },
  { id: "saves", i: "🧤🙌", hr: "Obrane golmana O/U", en: "Saves O/U" },
  { id: "dribbles", i: "🏃💨", hr: "Driblinzi O/U", en: "Dribbles O/U" },
  { id: "crosses", i: "✈↗", hr: "Centaršutevi O/U", en: "Crosses O/U" },
  { id: "longBalls", i: "🎯↗", hr: "Duge lopte O/U", en: "Long Balls O/U" },
  { id: "shortPasses", i: "🔄", hr: "Kratka dodavanja O/U", en: "Short Passes O/U" },
  { id: "interceptions", i: "✋", hr: "Presječene lopte O/U", en: "Interceptions O/U" },
  { id: "clearances", i: "🧹", hr: "Izbijanja O/U", en: "Clearances O/U" },
  { id: "blocks", i: "🧱", hr: "Blokirani udarci O/U", en: "Blocks O/U" },
  { id: "ownGoal", i: "😱⚽", hr: "Vlastiti gol", en: "Own Goal" },
  { id: "hattrick", i: "🎩⚽", hr: "Hat-trick", en: "Hat-trick" },
  { id: "scoreFirst", i: "🥇⚽", hr: "Koji tim prvi zabija", en: "Team to Score First" },
  { id: "scoreLast", i: "🏁⚽", hr: "Koji tim zadnji zabija", en: "Team to Score Last" },
  { id: "winEitherHalf", i: "🏆⏸▶", hr: "Pobjeda u barem 1 pol.", en: "Win Either Half" },
  { id: "bttsInBothH", i: "⚽⚽x2", hr: "Oba gol u OBA poluvremena", en: "BTTS in Both Halves" },
  { id: "goalFirst10", i: "⏱🔟", hr: "Gol u prvih 10 min", en: "Goal in First 10 Min" },
  { id: "goalLast10", i: "⏱🔚", hr: "Gol u zadnjih 10 min", en: "Goal in Last 10 Min" },
  { id: "goalAfter80", i: "⏱80+", hr: "Gol nakon 80. min", en: "Goal After 80th Min" },
  { id: "fgMethod", i: "🎯📐", hr: "Metoda prvog gola", en: "First Goal Method" },
  { id: "res_gg", i: "🎯+⚽⚽", hr: "Ishod + GG (kombinirano)", en: "Result + BTTS Combo" },
  { id: "res_o25", i: "🎯+📈", hr: "Ishod + Over 2.5", en: "Result + Over 2.5" },
  { id: "res_u25", i: "🎯+📉", hr: "Ishod + Under 2.5", en: "Result + Under 2.5" },
  { id: "asianTotal", i: "🀄", hr: "Azijski total golova", en: "Asian Total Goals" },
  { id: "euroHand", i: "🇪🇺±", hr: "Europski hendikep (3-way)", en: "European Handicap" },
  { id: "oddEven", i: "12/2", hr: "Ukupno: Paran/Neparan", en: "Odd/Even Total Goals" },
  { id: "highHalf", i: "📊⏱", hr: "Koje poluvrijeme gol-bogatije", en: "Highest Scoring Half" },
  { id: "team2p", i: "⚽⚽🏠✈", hr: "Tim zabija 2+ gola", en: "Team Scores 2+ Goals" },
  { id: "team3p", i: "⚽⚽⚽🏠✈", hr: "Tim zabija 3+ gola", en: "Team Scores 3+ Goals" },
  { id: "homeBH", i: "🏠⚽⚽", hr: "Domaćin gol u oba pol.", en: "Home Goal Both Halves" },
  { id: "awayBH", i: "✈⚽⚽", hr: "Gost gol u oba pol.", en: "Away Goal Both Halves" },
  { id: "exactMinute", i: "⏱🎯", hr: "Minuta prvog gola", en: "Exact Goal Minute" },
  { id: "aiBtts", i: "🤖⚽⚽", hr: "AI BTTS Prediktor", en: "AI BTTS Predictor" },
  { id: "aiOU25", i: "🤖📊2.5", hr: "AI Over/Under 2.5", en: "AI Over/Under 2.5" },
  { id: "ggOu25", i: "🎰GG+2.5", hr: "GG + Over 2.5 Kombinacija", en: "GG + Over 2.5 Combo" },
];
/** Bazne stope događaja (prosjek europskih liga) koje se koriguju unosom korisnika. */
export const EVENT_BASE: Record<string, number> = {
  comeback: 0.15,
  winFromBehind: 0.12,
  loseFromAhead: 0.1,
  bothHalves: 0.35,
  domBoth: 0.25,
  gostBoth: 0.15,
  cleanSheetH: 0.28,
  cleanSheetA: 0.2,
  firstHalfWin: 0.35,
  secondHalfWin: 0.3,
  drawHT: 0.28,
  penalty: 0.22,
  redCard: 0.15,
  ownGoal: 0.04,
  hattrick: 0.06,
};
/** Statistička tržišta: prosječna vrijednost po utakmici i zadana linija. */
export const STAT_BASE: Record<string, { base: number; line: number }> = {
  totalShots: { base: 24, line: 22.5 },
  shotsOnTarget: { base: 9, line: 8.5 },
  offsides: { base: 5, line: 4.5 },
  fouls: { base: 22, line: 20.5 },
  goalKicks: { base: 12, line: 11.5 },
  throwIns: { base: 36, line: 34.5 },
  subs: { base: 6, line: 5.5 },
  injuryTime: { base: 4, line: 3.5 },
  possession: { base: 50, line: 49.5 },
  passAccuracy: { base: 80, line: 78.5 },
  aerialDuels: { base: 40, line: 38.5 },
  tackles: { base: 28, line: 27.5 },
  saves: { base: 6, line: 5.5 },
  dribbles: { base: 18, line: 17.5 },
  crosses: { base: 22, line: 20.5 },
  longBalls: { base: 34, line: 32.5 },
  shortPasses: { base: 280, line: 270.5 },
  interceptions: { base: 15, line: 14.5 },
  clearances: { base: 24, line: 22.5 },
  blocks: { base: 8, line: 7.5 },
};
export type Settings = {
  fontSz: "sm" | "md" | "lg";
  compact: boolean;
  autoTheme: boolean;
  homeAdv: number;
  formW: number;
  h2hW: number;
  weatherOn: boolean;
};
export const DEFAULT_SETTINGS: Settings = {
  fontSz: "md",
  compact: false,
  autoTheme: false,
  homeAdv: 15,
  formW: 70,
  h2hW: 20,
  weatherOn: true,
};
export const LEAGUE_PRESETS: [string, string][] = [
  ["2.82", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Premier League (2.82)"],
  ["2.69", "🇪🇸 La Liga (2.69)"],
  ["2.79", "🇮🇹 Serie A (2.79)"],
  ["3.12", "🇩🇪 Bundesliga (3.12)"],
  ["2.78", "🇫🇷 Ligue 1 (2.78)"],
  ["3.18", "🇳🇱 Eredivisie (3.18)"],
  ["2.72", "🇵🇹 Primeira Liga (2.72)"],
  ["2.91", "🇭🇷 HNL (2.91)"],
  ["2.64", "🏴󠁧󠁢󠁥󠁮󠁧󠁿 Championship (2.64)"],
  ["3.05", "🇩🇪 2.Bundesliga (3.05)"],
  ["2.95", "🇧🇪 Belgian Pro (2.95)"],
  ["3.21", "🇦🇹 Austrian BL (3.21)"],
  ["2.97", "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scottish Prem (2.97)"],
  ["3.01", "🇺🇸 MLS (3.01)"],
  ["2.62", "🇲🇽 Liga MX (2.62)"],
  ["2.74", "🇹🇷 Süper Lig (2.74)"],
  ["2.56", "🇮🇹 Serie B (2.56)"],
  ["2.88", "🇨🇭 Swiss SL (2.88)"],
];
export const ELO_PRESETS: [string, string][] = [
  ["150", "🌟 Elite vs Mid (150)"],
  ["200", "🌟 Top vs Lower (200)"],
  ["100", "⚖️ Similar teams (100)"],
  ["50", "⚖️ Close match (50)"],
  ["0", "⚖️ Equal (0)"],
  ["-50", "📉 Home slight underdog (-50)"],
  ["-100", "📉 Home underdog (-100)"],
  ["-200", "📉 Home big underdog (-200)"],
];
export const LEAGUES: { name: string; avg: number }[] = [
  { name: "Premier League", avg: 2.82 },
  { name: "La Liga", avg: 2.69 },
  { name: "Serie A", avg: 2.79 },
  { name: "Bundesliga", avg: 3.12 },
  { name: "Ligue 1", avg: 2.78 },
  { name: "Eredivisie", avg: 3.18 },
  { name: "Primeira Liga", avg: 2.72 },
  { name: "HNL", avg: 2.91 },
  { name: "Championship", avg: 2.64 },
  { name: "Super Lig", avg: 2.74 },
  { name: "Bundesliga 2", avg: 3.05 },
  { name: "Serie B", avg: 2.56 },
  { name: "Ligue 2", avg: 2.61 },
  { name: "Scottish Prem", avg: 2.97 },
  { name: "MLS", avg: 3.01 },
  { name: "Liga MX", avg: 2.62 },
  { name: "Süper Lig", avg: 2.74 },
  { name: "Belgian Pro", avg: 2.95 },
  { name: "Austrian Bundesliga", avg: 3.21 },
  { name: "Swiss SL", avg: 2.88 },
];
export const TEAM_ELO: { name: string; elo: number }[] = [
  { name: "Manchester City", elo: 2050 },
  { name: "Real Madrid", elo: 2044 },
  { name: "Bayern Munich", elo: 2021 },
  { name: "Arsenal", elo: 2007 },
  { name: "Liverpool", elo: 2001 },
  { name: "Barcelona", elo: 1992 },
  { name: "Paris SG", elo: 1987 },
  { name: "Borussia Dortmund", elo: 1981 },
  { name: "Atletico Madrid", elo: 1975 },
  { name: "Inter Milan", elo: 1970 },
  { name: "Chelsea", elo: 1961 },
  { name: "Juventus", elo: 1956 },
  { name: "AC Milan", elo: 1953 },
  { name: "Napoli", elo: 1948 },
  { name: "Manchester United", elo: 1945 },
  { name: "Tottenham", elo: 1937 },
  { name: "Newcastle", elo: 1921 },
  { name: "Bayer Leverkusen", elo: 1919 },
  { name: "RB Leipzig", elo: 1915 },
  { name: "Benfica", elo: 1911 },
  { name: "Dinamo Zagreb", elo: 1786 },
  { name: "Hajduk Split", elo: 1712 },
  { name: "NK Rijeka", elo: 1665 },
  { name: "NK Osijek", elo: 1647 },
];
export const REFEREES: { name: string; cards: number; pens: number; style: string }[] = [
  { name: "Sandro Schärer", cards: 3.8, pens: 0.18, style: "strict" },
  { name: "Clément Turpin", cards: 4.1, pens: 0.22, style: "strict" },
  { name: "Slavko Vinčić", cards: 3.5, pens: 0.2, style: "avg" },
  { name: "Michael Oliver", cards: 3.2, pens: 0.25, style: "avg" },
  { name: "Felix Zwayer", cards: 3.9, pens: 0.21, style: "strict" },
  { name: "Carlos del Cerro Grande", cards: 4.3, pens: 0.19, style: "strict" },
  { name: "Anthony Taylor", cards: 3.4, pens: 0.23, style: "avg" },
  { name: "Daniele Orsato", cards: 3.1, pens: 0.24, style: "lenient" },
  { name: "Björn Kuipers", cards: 2.9, pens: 0.2, style: "lenient" },
  { name: "Danny Makkelie", cards: 3, pens: 0.22, style: "avg" },
];
